name: belatuk_rethinkdb
description: A dart driver for connecting to RethinkDB, the open-source database for the realtime web
version: 1.3.0
homepage: https://github.com/dart-backend/belatuk-rethinkdb
repository: https://github.com/dart-backend/belatuk-rethinkdb

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  protobuf: ^5.0.0
  fixnum: ^1.0.0
  convert: ^3.0.1
  hashlib: ^2.2.0
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.26.0
  lints: ^6.0.0