name: belatuk_rethinkdb
description: This is an unofficial driver for using RethinkDB in Dart
version: 1.0.0
homepage: https://github.com/dart-backend/belatuk_rethinkdb
repository: https://github.com/dart-backend/belatuk_rethinkdb

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  protobuf: ^3.1.0
  fixnum: ^1.0.0
  convert: ^3.0.1
  hashlib: ^1.17.0
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0